services:
  postgresql:
    image: "postgres:16.4-alpine3.20"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      DATABASE_PORT: 5432
      POSTGRES_DB: db
    volumes:
      - /postgres:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    volumes:
      - /redis:/usr/local/etc/redis
  bot:
    environment: 
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: pass
      DATABASE_HOST: postgresql
      DATABASE_NAME: db
      DATABASE_PORT: 5432
      TOKEN_TELEGRAM: token
      OPENAI_KEY: key
      OPENAI_ASST_KEY: key
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /bot:/usr/src/app/log/
   
